config/routes.rb
Rails.application.routes.draw do
  get 'users/update'

  devise_for :users
  resources :users, only: [:update]
  post 'users/downgrade'
  #Welcome section
  get 'welcome/index'
  get 'welcome/about'

  #wikis
  resources :wikis

  #Home Page
  root to: 'welcome#index'

  #Stripe charges
  resources :charges, only: [:new, :create]
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime
#  updated_at             :datetime
#  role                   :string
#

class User < ActiveRecord::Base
  
  after_create :set_as_standard

  has_many :wikis
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


# Implementation of Authorization

   USER_ROLES = {
    :admin => 'admin',
    :standard => 'standard',
    :premium => 'premium',
   }

#Setting the role
def set_as_admin
  self.role = USER_ROLES[:admin]
end

def set_as_standard
  self.role = USER_ROLES[:standard]
  self.save
  self.wikis.each do | wiki |
    wiki.update_attributes(private: false)
  end
end

def set_as_premium
  self.role = USER_ROLES[:premium]
end

#Defining permissions
def can_edit?(issue)
  true if (owns?(issue) || admin?)
end

def can_destroy?(issue)
  true if owns?(issue) || admin?
end

def can_update?(issue)
  true if owns?(issue) || admin?
end

def can_private?
  if premium? || admin?
    true
  else
    false
  end
end

#defining role methods

def owns?(issue)
  true if self.id == issue.user_id
end

def admin?
  true if self.role == USER_ROLES[:admin]
end

def premium?
  true if self.role == USER_ROLES[:premium]
end

def standard?
  true if self.role == USER_ROLES[:standard]
end

def role_name
  User.user_roles.key(self.role)
end

def self.user_roles
  USER_ROLES
end


end

app/models/wiki.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  private    :boolean
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Wiki < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader

  scope :visible_private, -> { where("private IS NULL OR private IS ?", false)}


  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :user, presence: true


  def unpublic_wikis(wiki)
    # if 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
  @stripe_btn_data = {
  key: "#{ Rails.configuration.stripe[:publishable_key] }",
  description: "Upgrade to Premium Account",
  amount: "5000"
  }
end

def create

  #Amount
  @amount = 5000
  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
    )

  charge = Stripe::Charge.create(
    customer: customer.id,
    amount: @amount,
    description: "Premium Membership - #{current_user.email}",
    currency: 'usd'
    )

  flash[:success] = "Thank you for upgrading, #{current_user.name}!"
  current_user.role = "premium"
  current_user.save!
  redirect_to edit_user_registration_path


rescue Stripe::CardError => e 
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def edit
end

def update
  if current_user.update_attributes(user_params)
    flash[:notice] = "User information updated"
    redirect_to edit_user_registration_path
    else
    flash[:error] = "Invalid user information"
    redirect_to edit_user_registration_path
  end
end

def show
end


def downgrade

  if current_user.set_as_standard
    flash[:notice] = "Successfully Downgraded"
    redirect_to edit_user_registration_path
  else
    flash[:error]= "There was an issue Downgrading, please try again."
    redirect_to edit_user_registration_path
  end
end



private

def user_params
  params.require(:user).permit(:name, :avatar)
end






end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  
  def index
    if current_user.can_private?
      @wikis = Wiki.includes(:user).paginate(page: params[:page], per_page: 10)
    else
      @wikis = Wiki.includes(:user).visible_private.paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end


  def create
    @wiki = current_user.wikis.build(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki Saved!"
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving your Wiki. Please try again."
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    if @wiki.update_attributes(wiki_params)
      redirect_to @wiki
    else
      flash[:error] = "There was an error updating your Wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted!."
      redirect_to wikis_path
    else
      flash[:error] = "Error deleting Wiki. Please try again."
      render :show
    end
  end

private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :user, :private, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_name
    "Jeremy Lam"
  end

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  

  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/_form.html.erb
 <%= form_tag charges_path do %>
   <h4>Click for instant gratification</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/charges/new.html.erb
<div class="row">
  <div class="col-md-8">
    <h2> Why Upgrade to Premium? </h2>
    <br>
    <h3>See all the latest private Wiki's.</h3>
    <h3>Create your own private Wiki's that only Premium Members can see.</h3>
    <h3>Feel happy, Just really happy.</h3>
    <br>
  </div>
  <div class="col-md-4">
    <%= render partial: 'form' %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlohaWiki</title>
  <meta name="viewport" content="width=device-width, intial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs", role="navigation">
        <div class="pull-left">
        <%= link_to welcome_index_path, class: "btn btn-primary btn-sm" do %><span class= "glyphicon glyphicon-home"></span>
        <% end %>
        <% if current_user.present? %>
        <%= link_to wikis_path, class: 'btn btn-primary btn-sm' do %><span class= "glyphicon glyphicon-book"></span>
        <% end %>
        <% end %>
      </div>
        <div class="pull-right">
      <% if current_user %>
      <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
        Hello <%= link_to current_user.name, edit_user_registration_path %>!
        <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
        <span class="glyphicon glyphicon-user"></span>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-small' do %>
        <span class="glyphicon glyphicon-log-out"></span>
        <% end %> 
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
  </div>
</ul>
  

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;
            <span class="glyphicon glyphicon-ok" aria-hidden="true">
          </span> 
        </button>
        <%= flash[:notice] %>
      </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;
              <span class="glyphicon glyphicon-remove" aria-hidden="true">
          </span> 
        </button>
        <%= flash[:error] %>
      </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;
              <span class="glyphicon glyphicon-warning-sign " aria-hidden="true">
          </span> 
        </button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>        
  </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>About</h1>
<p>Created by: <%= my_name %></p>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12" id="aloha">
    <p id="index-title">AlohaWiki</p>
    <p id="sub-index-title">Your Resource for all things Hawaii</p>
    <div class="col-md-12" id="center-bn">
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          Get Started <span class="caret"></span>
        </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Create a Wiki", new_wiki_path %></li>
            <li><%= link_to "Wiki's", wikis_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_session_path %></li>
          </ul>
       </div>
    </div>
  </div>
</div>
</div>
</div>
</body>
<br>
<div class = "container">
  <div class="row">
    <div class="col-md-4" id="subbox">
      <h3>Latest Wiki's</h3>
    </div>
    <div class="col-md-4" id="subbox">
      <span class="glyphicon glyphicon-search"></span>
    </div>
    <div class="col-md-4" id="subbox">
      <h3>Placeholder</h3>
    </div>
  </div>



  

app/views/wikis/_form.html.erb
  <%= form_for @wiki do |f| %>
    <% if @wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(@wiki.errors.count, "error") %>.</h4>
      <ul>
        <% @wiki.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class= "col-md-8">
      <%= form_group_tag(@wiki.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki Title" %>
    <% end %>
      <%= form_group_tag(@wiki.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki Content" %>
      <% end %>
        <% if current_user.can_private? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private Wiki?
          <% end %>
          <% end %>
        </div>
        <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      </div>
      <div class= 'col-md-4'>
        <div class="form-group">
        <% if @wiki.image? %>
        <%= image_tag(@wiki.image.url ) %>
        <% end %>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
        
      <% end %>
    </div>
    

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class = "row">
  <div class = "col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wiki's</h1>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wik| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <% if wik.title? %>
            <%= image_tag(wik.image.thumb.url) %>
            <% end %>
            <%= link_to wik.title, wik %>
          </h4>
        </div>
      </div>
      <% end %>
      <%= will_paginate @wikis %>
    </div>
  
    <div class="col-md-4">
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          Action <span class="caret"></span>
        </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "New Wiki", new_wiki_path%></li>
            <li class="divider"></li>
          </ul>
    </div>
  </div>

app/views/wikis/new.html.erb
<h1>Create your new Aloha Wiki</h1>
<div class = "row">
  <div class = "col-md-12">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1><%= markdown_to_html @wiki.title %></h1>
    <small>
      <%= image_tag(@wiki.user.avatar.tiny.url) if @wiki.user.avatar? %>
      submitted <%= time_ago_in_words(@wiki.created_at) %> ago by
      <%= @wiki.user.name %>
    </small>
    <div class="h_line"></div>
    <p><%= markdown_to_html @wiki.body %></p>
  </div>

  <div class="col-md-4">
    <div class='form-group'>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          Action <span class="caret"></span>
        </button>
          <ul class="dropdown-menu" role="menu">
            <% if current_user.can_edit?(@wiki) %>
            <li><%= link_to "Edit Wiki", edit_wiki_path(@wiki) %></li>
            <% else %>
            <p id="menu-word">Cannot Edit</p>
            <% end %>
            <% if current_user.can_edit?(@wiki) %>
            <li><%= link_to "Delete Wiki", wiki_path(@wiki), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>
            <% else %>
            <p id="menu-word">Cannot Delete</p>
            <% end %>

            <li class="divider"></li> 
          </ul>
        </div>
      </div>
        <br>
        <div class = 'form-group'>
          <% if @wiki.image? %>
          <%= image_tag(@wiki.image.url) %>
          <% end %>
        </div>
      </div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>